## I use cacheSolve to actually solve the inverse matrices or just retrieve them from cache.
## If the inverse matrix is already solved and saved in cache, it will be returned directly from cache;
## if not, cacheSolve will solve the inverse matrix and save it in cache, 
## and the solution could be retrieved next time when I call cacheSolve.

## makeCacheMatrix:
## This is a function which makes a list containing four functions.
## The argument "x" is to put a matrix to be solved.
## First the function makes a NULL object "invx", which is going to put the solution.
## Then there are four functions listed:
## (1) set: sets the matrix you want to solve, and makes sure "invx" is clear (by "invx<<-NULL").
## (2) get: gets the matrix.
## (3) setInvx: saves the inverse matrix solved in cache.
## (4) getInvx: gets the inverse matrix from cache.

makeCacheMatrix <- function(x = matrix()) {
        invx<-NULL
        
        set<-function(y){
                x<<-y
                invx<<-NULL
        }
        get<-function(){
                x
        }
        setInvx<-function(Invxs){
                invx<<-Invxs
        }
        getInvx<-function(){
                invx
        }
        
        list(set=set, get=get, setInvx=setInvx, getInvx=getInvx)
}


## cacheSolve:
## This is a function which solves or just retrieves the inverse matrix from cache.
## The argument x is to put the list generated by "makeCacheMatrix".
## First, the function loads the inverse function from cache.
## If there has been a solution (i.e. is.null(invx)==FALSE),
## the function prints a message "getting cached data" and returns invx.
## If there is nothing in cache, the function will solve the inverse matrix and then save it.
## The function cacheSolve "get"s the matrix from makeCacheMatrix,
## and by "qr.solve" it could solve the inverse function.
## The solution is going to be saved by "setInvx",
## then (since it still has to print the solution) printing the solution.

cacheSolve <- function(x, ...) {
        invx<-x$getInvx()
        
        if(!is.null(invx)){
                message("getting cached data")
                return(invx)                
        }
        
        data<-x$get()
        invx<-qr.solve(data)
        x$setInvx(invx)
        invx
}
